server:
  port: 8080
mybatis:
  mapper-locations: # 所有的mapper映射文件
  - classpath:mapping/*.xml
spring:
  application:
    name: gs-edu-provider-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://10.1.137.225:3306/gs_edu?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root # 数据库用户名
    password: root # 数据库连接密码
  security:
    user:
      name: admin
      password: admin
      roles: USER
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gs-edu-provider-newproduct
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
info:
  app.name: gs-edu-provider-product
  company.name: gsedu
  build.artifactId: gs-edu-provider-product
  build.modelVersion: 4.0.0
